//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AssetResponseMsgWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AssetResponseMsg), typeof(U3DEventFrame.MsgBase));
		L.RegFunction("GetBundleName", GetBundleName);
		L.RegFunction("DebugBundle", DebugBundle);
		L.RegFunction("GetBundleResByIndex", GetBundleResByIndex);
		L.RegFunction("GetBundleRes", GetBundleRes);
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("New", _CreateAssetResponseMsg);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAssetResponseMsg(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				BundleRequest arg0 = (BundleRequest)ToLua.CheckObject<BundleRequest>(L, 1);
				AssetResponseMsg obj = new AssetResponseMsg(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: AssetResponseMsg.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBundleName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AssetResponseMsg obj = (AssetResponseMsg)ToLua.CheckObject<AssetResponseMsg>(L, 1);
			string[] o = obj.GetBundleName();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DebugBundle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AssetResponseMsg obj = (AssetResponseMsg)ToLua.CheckObject<AssetResponseMsg>(L, 1);
			obj.DebugBundle();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBundleResByIndex(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AssetResponseMsg obj = (AssetResponseMsg)ToLua.CheckObject<AssetResponseMsg>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			UnityEngine.Object[] o = obj.GetBundleResByIndex(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBundleRes(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AssetResponseMsg obj = (AssetResponseMsg)ToLua.CheckObject<AssetResponseMsg>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			UnityEngine.Object[] o = obj.GetBundleRes(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AssetResponseMsg obj = (AssetResponseMsg)ToLua.CheckObject<AssetResponseMsg>(L, 1);
			obj.Dispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

