//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AssetRequesetMsgWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AssetRequesetMsg), typeof(U3DEventFrame.MsgBase));
		L.RegFunction("ChangeEventMsg", ChangeEventMsg);
		L.RegFunction("New", _CreateAssetRequesetMsg);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("requesetInfo", get_requesetInfo, set_requesetInfo);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAssetRequesetMsg(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 7)
			{
				ushort arg0 = (ushort)LuaDLL.luaL_checknumber(L, 1);
				ushort arg1 = (ushort)LuaDLL.luaL_checknumber(L, 2);
				string arg2 = ToLua.CheckString(L, 3);
				string[] arg3 = ToLua.CheckStringArray(L, 4);
				string[] arg4 = ToLua.CheckStringArray(L, 5);
				bool[] arg5 = ToLua.CheckBoolArray(L, 6);
				int[] arg6 = ToLua.CheckNumberArray<int>(L, 7);
				AssetRequesetMsg obj = new AssetRequesetMsg(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: AssetRequesetMsg.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ChangeEventMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 7);
			AssetRequesetMsg obj = (AssetRequesetMsg)ToLua.CheckObject<AssetRequesetMsg>(L, 1);
			ushort arg0 = (ushort)LuaDLL.luaL_checknumber(L, 2);
			ushort arg1 = (ushort)LuaDLL.luaL_checknumber(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			string[] arg3 = ToLua.CheckStringArray(L, 5);
			string[][] arg4 = ToLua.CheckObjectArray<string[]>(L, 6);
			bool[][] arg5 = ToLua.CheckObjectArray<bool[]>(L, 7);
			obj.ChangeEventMsg(arg0, arg1, arg2, arg3, arg4, arg5);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_requesetInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AssetRequesetMsg obj = (AssetRequesetMsg)o;
			AssetRequesetInfo ret = obj.requesetInfo;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index requesetInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_requesetInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AssetRequesetMsg obj = (AssetRequesetMsg)o;
			AssetRequesetInfo arg0 = (AssetRequesetInfo)ToLua.CheckObject<AssetRequesetInfo>(L, 2);
			obj.requesetInfo = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index requesetInfo on a nil value");
		}
	}
}

