//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class RoateSelfWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(RoateSelf), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("ShowMuti", ShowMuti);
		L.RegFunction("Rote", Rote);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowMuti(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			RoateSelf obj = (RoateSelf)ToLua.CheckObject<RoateSelf>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.ShowMuti(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Rote(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			RoateSelf obj = (RoateSelf)ToLua.CheckObject<RoateSelf>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.Rote(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

