//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class U3DEventFrame_ManagerBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(U3DEventFrame.ManagerBase), typeof(U3DEventFrame.MonoBase));
		L.RegFunction("ProcessSendBackMsg", ProcessSendBackMsg);
		L.RegFunction("BackMsgUpdate", BackMsgUpdate);
		L.RegFunction("InitialBackMsg", InitialBackMsg);
		L.RegFunction("ProcessEvent", ProcessEvent);
		L.RegFunction("UnRegistMsg", UnRegistMsg);
		L.RegFunction("RegistMsg", RegistMsg);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("eventTree", get_eventTree, set_eventTree);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ProcessSendBackMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			U3DEventFrame.ManagerBase obj = (U3DEventFrame.ManagerBase)ToLua.CheckObject<U3DEventFrame.ManagerBase>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.ProcessSendBackMsg(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int BackMsgUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			U3DEventFrame.ManagerBase obj = (U3DEventFrame.ManagerBase)ToLua.CheckObject<U3DEventFrame.ManagerBase>(L, 1);
			obj.BackMsgUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitialBackMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			U3DEventFrame.ManagerBase obj = (U3DEventFrame.ManagerBase)ToLua.CheckObject<U3DEventFrame.ManagerBase>(L, 1);
			obj.InitialBackMsg();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ProcessEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			U3DEventFrame.ManagerBase obj = (U3DEventFrame.ManagerBase)ToLua.CheckObject<U3DEventFrame.ManagerBase>(L, 1);
			U3DEventFrame.MsgBase arg0 = (U3DEventFrame.MsgBase)ToLua.CheckObject<U3DEventFrame.MsgBase>(L, 2);
			obj.ProcessEvent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegistMsg(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			U3DEventFrame.ManagerBase obj = (U3DEventFrame.ManagerBase)ToLua.CheckObject<U3DEventFrame.ManagerBase>(L, 1);
			U3DEventFrame.MonoBase arg0 = (U3DEventFrame.MonoBase)ToLua.CheckObject<U3DEventFrame.MonoBase>(L, 2);
			ushort[] arg1 = ToLua.CheckParamsNumber<ushort>(L, 3, count - 2);
			obj.UnRegistMsg(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegistMsg(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			U3DEventFrame.ManagerBase obj = (U3DEventFrame.ManagerBase)ToLua.CheckObject<U3DEventFrame.ManagerBase>(L, 1);
			U3DEventFrame.MonoBase arg0 = (U3DEventFrame.MonoBase)ToLua.CheckObject<U3DEventFrame.MonoBase>(L, 2);
			ushort[] arg1 = ToLua.CheckParamsNumber<ushort>(L, 3, count - 2);
			obj.RegistMsg(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eventTree(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			U3DEventFrame.ManagerBase obj = (U3DEventFrame.ManagerBase)o;
			System.Collections.Generic.Dictionary<ushort,U3DEventFrame.EventNode> ret = obj.eventTree;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eventTree on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_eventTree(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			U3DEventFrame.ManagerBase obj = (U3DEventFrame.ManagerBase)o;
			System.Collections.Generic.Dictionary<ushort,U3DEventFrame.EventNode> arg0 = (System.Collections.Generic.Dictionary<ushort,U3DEventFrame.EventNode>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Dictionary<ushort,U3DEventFrame.EventNode>));
			obj.eventTree = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eventTree on a nil value");
		}
	}
}

