//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class U3DEventFrame_UIManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(U3DEventFrame.UIManager), typeof(U3DEventFrame.ManagerBase));
		L.RegFunction("SendMsg", SendMsg);
		L.RegFunction("RegistGameObject", RegistGameObject);
		L.RegFunction("UnRegistGameObject", UnRegistGameObject);
		L.RegFunction("UnRegistPanelGameObject", UnRegistPanelGameObject);
		L.RegFunction("GetGameObject", GetGameObject);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("instance", get_instance, set_instance);
		L.RegVar("SonMembers", get_SonMembers, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendMsg(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				U3DEventFrame.UIManager obj = (U3DEventFrame.UIManager)ToLua.CheckObject<U3DEventFrame.UIManager>(L, 1);
				U3DEventFrame.MsgBase arg0 = (U3DEventFrame.MsgBase)ToLua.CheckObject<U3DEventFrame.MsgBase>(L, 2);
				obj.SendMsg(arg0);
				return 0;
			}
			else if (count == 3)
			{
				U3DEventFrame.UIManager obj = (U3DEventFrame.UIManager)ToLua.CheckObject<U3DEventFrame.UIManager>(L, 1);
				U3DEventFrame.MsgBase arg0 = (U3DEventFrame.MsgBase)ToLua.CheckObject<U3DEventFrame.MsgBase>(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				obj.SendMsg(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: U3DEventFrame.UIManager.SendMsg");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegistGameObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			U3DEventFrame.UIManager obj = (U3DEventFrame.UIManager)ToLua.CheckObject<U3DEventFrame.UIManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			UnityEngine.GameObject arg2 = (UnityEngine.GameObject)ToLua.CheckObject(L, 4, typeof(UnityEngine.GameObject));
			obj.RegistGameObject(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegistGameObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			U3DEventFrame.UIManager obj = (U3DEventFrame.UIManager)ToLua.CheckObject<U3DEventFrame.UIManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.UnRegistGameObject(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegistPanelGameObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			U3DEventFrame.UIManager obj = (U3DEventFrame.UIManager)ToLua.CheckObject<U3DEventFrame.UIManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.UnRegistPanelGameObject(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetGameObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			U3DEventFrame.UIManager obj = (U3DEventFrame.UIManager)ToLua.CheckObject<U3DEventFrame.UIManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			UnityEngine.GameObject o = obj.GetGameObject(arg0, arg1);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, U3DEventFrame.UIManager.instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SonMembers(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			U3DEventFrame.UIManager obj = (U3DEventFrame.UIManager)o;
			System.Collections.Generic.Dictionary<string,System.Collections.Generic.Dictionary<string,UnityEngine.GameObject>> ret = obj.SonMembers;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SonMembers on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_instance(IntPtr L)
	{
		try
		{
			U3DEventFrame.UIManager arg0 = (U3DEventFrame.UIManager)ToLua.CheckObject<U3DEventFrame.UIManager>(L, 2);
			U3DEventFrame.UIManager.instance = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

