//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class U3DEventFrame_MsgBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(U3DEventFrame.MsgBase), typeof(System.Object));
		L.RegFunction("ChangeEventId", ChangeEventId);
		L.RegFunction("GetNetBytes", GetNetBytes);
		L.RegFunction("GetState", GetState);
		L.RegFunction("GetManager", GetManager);
		L.RegFunction("New", _CreateU3DEventFrame_MsgBase);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("msgId", get_msgId, set_msgId);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateU3DEventFrame_MsgBase(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				U3DEventFrame.MsgBase obj = new U3DEventFrame.MsgBase();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<byte[]>(L, 1))
			{
				byte[] arg0 = ToLua.CheckByteBuffer(L, 1);
				U3DEventFrame.MsgBase obj = new U3DEventFrame.MsgBase(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<ushort>(L, 1))
			{
				ushort arg0 = (ushort)LuaDLL.lua_tonumber(L, 1);
				U3DEventFrame.MsgBase obj = new U3DEventFrame.MsgBase(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: U3DEventFrame.MsgBase.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ChangeEventId(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			U3DEventFrame.MsgBase obj = (U3DEventFrame.MsgBase)ToLua.CheckObject<U3DEventFrame.MsgBase>(L, 1);
			ushort arg0 = (ushort)LuaDLL.luaL_checknumber(L, 2);
			obj.ChangeEventId(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNetBytes(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			U3DEventFrame.MsgBase obj = (U3DEventFrame.MsgBase)ToLua.CheckObject<U3DEventFrame.MsgBase>(L, 1);
			byte[] o = obj.GetNetBytes();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetState(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			U3DEventFrame.MsgBase obj = (U3DEventFrame.MsgBase)ToLua.CheckObject<U3DEventFrame.MsgBase>(L, 1);
			byte o = obj.GetState();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetManager(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			U3DEventFrame.MsgBase obj = (U3DEventFrame.MsgBase)ToLua.CheckObject<U3DEventFrame.MsgBase>(L, 1);
			int o = obj.GetManager();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_msgId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			U3DEventFrame.MsgBase obj = (U3DEventFrame.MsgBase)o;
			ushort ret = obj.msgId;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index msgId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_msgId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			U3DEventFrame.MsgBase obj = (U3DEventFrame.MsgBase)o;
			ushort arg0 = (ushort)LuaDLL.luaL_checknumber(L, 2);
			obj.msgId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index msgId on a nil value");
		}
	}
}

